### ISSUE TITLE
TypeError when searching only one field

### ISSUE THREAD

**Issue by arturjzapater** [carolinejold/github-networking#1]
If you try to search selecting only language or location, a `TypeError` will appear in the console saying that `DropDown` can't access the property `label` of `null`.

As far as I understand, this happens because `onSubmit` in the [Dropdown](https://github.com/carolinejold/github-networking/blob/master/src/components/Dropdown.js) component is trying to access a property from an object, but the current value is `null`.

I imagine that the intention behind the app is that both fields should be filled before performing a search. But it can be confusing for a distracted user who only fills one field to see nothing happen.

So I would suggest either performing some checks in `onSubmit` before calling `setResultsData` and give feedback if the input is wrong, or simply load the page with predetermined values for language and location.

**Comment by carolinejold** [comment]
Hi Artur, thanks for the advice! I’ll look into it later on :) also, just out of interest, how did you message me with this feedback? I received it as an email but can’t seem to access it anywhere on GitHub.

**Comment by arturjzapater** [comment]
I'm always happy to help^^

To give the feedback I simply opened a new issue on you repository's [issues](https://github.com/carolinejold/github-networking/issues). You can see it and reply to it from there.

**Comment by carolinejold** [comment]
I appreciate it! All fixed now :)
